บท 7 แบบฝึกหัด

In [56]:
coffee_shop_data = {
    'วันที่': ['1/1/24', '01-01-2024', '2024-01-01', '1 มค 24'],
    'เมนู': ['Latte', 'ลาเต้', 'Latte Hot', 'ลาเต้ร้อน'],
    'ขนาด': ['M', 'กลาง', 'Medium', 'M'],
    'ราคา': [60, 60, None, 60],
    'เวลา': ['08:30', '12.00', '14:30', '9:00']
}
data_frame_coffee_shop = pd.DataFrame(coffee_shop_data)

ทำให้ข้อมูลเป็นมาตรฐานเดียวกัน // หาค่าเฉลี่ยของราคา

In [57]:
def Standard_date (day):
    if day in ['1/1/24', '01-01-2024', '2024-01-01', '1 มค 24']:
        return '01/มค/2024'
def Standard_menu(menu):
    if menu in ['Latte', 'ลาเต้', 'Latte Hot', 'ลาเต้ร้อน']:
        return 'Latte Hot 1 Cup'
def Standard_Cup(cup):
    if cup in ['M', 'กลาง', 'Medium', 'M','m']:
        return 'Medium Cup'
def Standard_time(time):
    if pd.isna(time):
        return '08:00'
    time = str(time).replace('.',':')
    if len(time.split(':')[0]) == 1:
        time = '0' + time
    return time;

mean_price = data_frame_coffee_shop['ราคา'].mean()

In [58]:
print("="*50)
print("ก่อนแปลงเปลี่ยนค่าต่างๆ")
print("="*50)
print(data_frame_coffee_shop)
print("="*50)
print()

==================================================
ก่อนแปลงเปลี่ยนค่าต่างๆ
==================================================
       วันที่       เมนู    ขนาด  ราคา   เวลา
0      1/1/24      Latte       M  60.0  08:30
1  01-01-2024      ลาเต้    กลาง  60.0  12.00
2  2024-01-01  Latte Hot  Medium   NaN  14:30
3     1 มค 24  ลาเต้ร้อน       M  60.0   9:00
==================================================

In [59]:
data_frame_coffee_shop['ขนาด'] = data_frame_coffee_shop['ขนาด'].apply(Standard_Cup)
data_frame_coffee_shop['วันที่'] = data_frame_coffee_shop['วันที่'].apply(Standard_date)
data_frame_coffee_shop['เวลา'] = data_frame_coffee_shop['เวลา'].apply(Standard_time)
data_frame_coffee_shop['เมนู'] = data_frame_coffee_shop['เมนู'].apply(Standard_menu)

data_frame_coffee_shop['ราคา'].fillna(mean_price,inplace=True)

In [60]:
print("="*50)
print("หลังแปลงเปลี่ยนค่าต่างๆ")
print("="*50)
print(data_frame_coffee_shop)
print("="*50)
print()

==================================================
หลังแปลงเปลี่ยนค่าต่างๆ
==================================================
       วันที่             เมนู        ขนาด  ราคา   เวลา
0  01/มค/2024  Latte Hot 1 Cup  Medium Cup  60.0  08:30
1  01/มค/2024  Latte Hot 1 Cup  Medium Cup  60.0  12:00
2  01/มค/2024  Latte Hot 1 Cup  Medium Cup  60.0  14:30
3  01/มค/2024  Latte Hot 1 Cup  Medium Cup  60.0  09:00
==================================================

เป็นการนำเข้าไลบารี pandas(สำหรับจัดการข้อมูล),numpy(ไว้ใช้ในการคำนวณ)

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

#นำข้อมูลเข้าจากไฟล์ student.csv
df_csv = pd.read_csv("student.csv")

#เพิ่มวันที่ลงทะเบียน
base_date = datetime(2024, 1, 15)
df_csv['วันที่ลงทะเบียน'] = [base_date + timedelta(days=np.random.randint(-30, 30))
                                for _ in range(20)]

แสดงข้อมูล และปัญหาที่พบในข้อมูลนี้

In [6]:
print("="*50)
print("🎯 ข้อมูลหลัก ใน Assiginment นี้")
print("="*50)
print(df_csv)
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {df_csv.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {df_csv[df_csv['อายุ'] > 100]['อายุ'].values if any(df_csv['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {df_csv[(df_csv['GPA'] < 0) | (df_csv['GPA'] > 4)]['GPA'].values if any((df_csv['GPA'] < 0) | (df_csv['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {df_csv['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {df_csv['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก ใน Assiginment นี้
==================================================
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-02-06
1         58.0                     20.0      2024-01-31
2          NaN                     25.0      2024-01-30
3         70.0                     10.0      2023-12-24
4         52.0                     30.0      2023-12-30
5         75.0                     12.0      2023-12-19
6         48.0                     35.0      2024-01-31
7         82.0                     18.0      2024-01-19
8         55.0                     22.0      2024-01-13
9         60.0                     28.0      2024-01-26
10        68.0                      NaN      2024-02-05
11         NaN                     16.0      2023-12-25
12        72.0                     24.0      2024-01-22
13        54.0                     19.0      2024-01-14
14        56.0                     26.0      2024-01-06
15        78.0                     14.0      2024-01-25
16        62.0                     21.0      2024-01-29
17        50.0                     27.0      2024-02-02
18        76.0                      NaN      2023-12-21
19        64.0                     23.0      2023-12-21

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 15 ค่า
- อายุผิดปกติ: [150.]
- GPA ผิดปกติ: [-1.   4.5]
- รูปแบบการเขียนคณะ: 14 แบบ
- รูปแบบการเขียนเพศ: 8 แบบ

เก็บสำเนาข้อมูลต้นฉบับ

In [7]:
df_original = df_csv.copy()

วิเคราะห์ข้อมูลของ df_master ที่ได้สร้างเอาไว้

In [8]:
print("="*50)
print("📋 ข้อมูลทั่วไปของ Dataset")
print("="*50)
df_csv.info()

print("\n" + "="*50)
print("📊 สถิติเชิงพรรณนา")
print("="*50)
print(df_csv.describe())

==================================================
📋 ข้อมูลทั่วไปของ Dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   รหัสนักศึกษา             20 non-null     int64
 1   ชื่อ                     19 non-null     object
 2   อายุ                     17 non-null     float64
 3   เพศ                      18 non-null     object
 4   คณะ                      18 non-null     object
 5   GPA                      18 non-null     float64
 6   ส่วนสูง_cm               19 non-null     float64
 7   น้ำหนัก_kg               18 non-null     float64
 8   ชั่วโมงเรียน_ต่อสัปดาห์  18 non-null     float64
 9   วันที่ลงทะเบียน          20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(1), object(3)
memory usage: 1.7+ KB

==================================================
📊 สถิติเชิงพรรณนา
==================================================
       รหัสนักศึกษา        อายุ        GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
count      20.00000   17.000000  18.000000   19.000000   18.000000
mean    64010.50000   28.470588   3.246111  167.684211   63.611111
min     64001.00000   19.000000  -1.000000  158.000000   48.000000
25%     64005.75000   20.000000   3.215000  163.500000   55.250000
50%     64010.50000   21.000000   3.450000  168.000000   63.000000
75%     64015.25000   22.000000   3.670000  171.500000   71.500000
max     64020.00000  150.000000   4.500000  180.000000   82.000000
std         5.91608   31.337114   1.123326    5.706260   10.279270

       ชั่วโมงเรียน_ต่อสัปดาห์      วันที่ลงทะเบียน
count                18.000000                   20
mean                 21.388889  2024-01-15 07:12:00
min                  10.000000  2023-12-19 00:00:00
25%                  16.500000  2023-12-28 18:00:00
50%                  21.500000  2024-01-20 12:00:00
75%                  25.750000  2024-01-30 06:00:00
max                  35.000000  2024-02-06 00:00:00
std                   6.598920                  NaN

ตรวจสอบค่าหายในแต่ละคอลัมน์

In [9]:
missing_counts = df_csv.isnull().sum()
print("\n❌ ค่าหายในแต่ละคอลัมน์:")
for col, count in missing_counts[missing_counts > 0].items():
    percentage = (count / len(df_csv)) * 100
    print(f"   - {col}: {count} ค่า ({percentage:.1f}%)")

❌ ค่าหายในแต่ละคอลัมน์:
   - ชื่อ: 1 ค่า (5.0%)
   - อายุ: 3 ค่า (15.0%)
   - เพศ: 2 ค่า (10.0%)
   - คณะ: 2 ค่า (10.0%)
   - GPA: 2 ค่า (10.0%)
   - ส่วนสูง_cm: 1 ค่า (5.0%)
   - น้ำหนัก_kg: 2 ค่า (10.0%)
   - ชั่วโมงเรียน_ต่อสัปดาห์: 2 ค่า (10.0%)

เติมอายุ,ส่วนสูง,น้ำหนัก ที่หายไปด้วยค่าเฉลี่ย

In [11]:
mean_age = df_csv['อายุ'].mean()
mean_height = df_csv['ส่วนสูง_cm'].mean()
mean_weight = df_csv['น้ำหนัก_kg'].mean()
mean_hour = df_csv['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()
df_csv['อายุ'].fillna(mean_age, inplace=True)
df_csv['ส่วนสูง_cm'].fillna(mean_height, inplace=True)
df_csv['น้ำหนัก_kg'].fillna(mean_weight, inplace=True)
df_csv['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hour, inplace=True)

In [13]:
print(df_csv)

    รหัสนักศึกษา      ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001     สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002    สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003       NaN   28.470588    Male         Science  3.67
3          64004  สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005      สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006     กานต์  150.000000     ชาย     Engineering  3.12
6          64007     กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008      จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009    ชนาธิป   23.000000       M            Arts  3.34
9          64010      ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011      ธีระ   28.470588     NaN             NaN  3.78
11         64012       นภา   22.000000     ชาย           วิทย์   NaN
12         64013     บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014     ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015     พิมพ์   22.000000  Female             Sci  3.67
15         64016      ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017      มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018      ยุพา   21.000000    หญิง             NaN  3.23
18         64019     รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020     ลัดดา   22.000000     NaN         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0   170.000000   65.000000                15.000000      2024-02-06
1   165.000000   58.000000                20.000000      2024-01-31
2   175.000000   63.611111                25.000000      2024-01-30
3   168.000000   70.000000                10.000000      2023-12-24
4   160.000000   52.000000                30.000000      2023-12-30
5   172.000000   75.000000                12.000000      2023-12-19
6   158.000000   48.000000                35.000000      2024-01-31
7   180.000000   82.000000                18.000000      2024-01-19
8   163.000000   55.000000                22.000000      2024-01-13
9   167.000000   60.000000                28.000000      2024-01-26
10  167.684211   68.000000                21.388889      2024-02-05
11  171.000000   63.611111                16.000000      2023-12-25
12  169.000000   72.000000                24.000000      2024-01-22
13  164.000000   54.000000                19.000000      2024-01-14
14  162.000000   56.000000                26.000000      2024-01-06
15  173.000000   78.000000                14.000000      2024-01-25
16  166.000000   62.000000                21.000000      2024-01-29
17  161.000000   50.000000                27.000000      2024-02-02
18  174.000000   76.000000                21.388889      2023-12-21
19  168.000000   64.000000                23.000000      2023-12-21

ทำให้ข้อมูลเป็นมาตรฐานเดียวกัน ร่วมใส่ข้อมูลให้เป็นมาตรฐานเดียวกัน

In [15]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science','Sci', 'คณะวิทยาศาสตร์']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts','Liberal Arts']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวกรรม','วิศวฯ', 'Engineering','วิศวะ', 'วิศวกรรมศาสตร์']:
        return 'วิศวกรรมศาสตร์'
    else:
        return name
df_csv['คณะ'] = df_csv['คณะ'].apply(standardize_faculty)

def standardize_sex(name):
    if name in ['ชาย','ช','M','Male']:
        return 'ชาย'
    elif name in ['หญิง', 'ญ', 'F','Female']:
        return 'หญิง'
    else:
        return name
df_csv['เพศ'] = df_csv['เพศ'].apply(standardize_sex)

เติม คณะ,เพศ ที่หายไปโดยอิงจากฐานนิยม

In [16]:
df_csv['คณะ'].fillna(df_csv['คณะ'].mode()[0], inplace=True)
df_csv['เพศ'].fillna(df_csv['เพศ'].mode()[0], inplace=True)

In [17]:
print(df_csv)

    รหัสนักศึกษา      ชื่อ        อายุ   เพศ             คณะ   GPA  \
0          64001     สมชาย   20.000000   ชาย     วิทยาศาสตร์  3.21
1          64002    สมหญิง   21.000000  หญิง     วิทยาศาสตร์  3.45
2          64003       NaN   28.470588   ชาย     วิทยาศาสตร์  3.67
3          64004  สมศักดิ์   22.000000   ชาย     วิทยาศาสตร์ -1.00
4          64005      สมใจ   19.000000  หญิง  วิศวกรรมศาสตร์  3.89
5          64006     กานต์  150.000000   ชาย  วิศวกรรมศาสตร์  3.12
6          64007     กิตติ   21.000000  หญิง  วิศวกรรมศาสตร์  4.50
7          64008      จิรา   20.000000  หญิง      ศิลปศาสตร์  2.98
8          64009    ชนาธิป   23.000000   ชาย      ศิลปศาสตร์  3.34
9          64010      ดารา   21.000000  หญิง      ศิลปศาสตร์  3.56
10         64011      ธีระ   28.470588   ชาย     วิทยาศาสตร์  3.78
11         64012       นภา   22.000000   ชาย     วิทยาศาสตร์   NaN
12         64013     บุญมี   20.000000  หญิง  วิศวกรรมศาสตร์  3.23
13         64014     ปรีชา   21.000000   ชาย      ศิลปศาสตร์  3.45
14         64015     พิมพ์   22.000000  หญิง     วิทยาศาสตร์  3.67
15         64016      ภูมิ   19.000000   ชาย     วิทยาศาสตร์  3.89
16         64017      มานี   20.000000  หญิง  วิศวกรรมศาสตร์  3.01
17         64018      ยุพา   21.000000  หญิง     วิทยาศาสตร์  3.23
18         64019     รัตนา   28.470588   ชาย      ศิลปศาสตร์   NaN
19         64020     ลัดดา   22.000000   ชาย     วิทยาศาสตร์  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0   170.000000   65.000000                15.000000      2024-02-06
1   165.000000   58.000000                20.000000      2024-01-31
2   175.000000   63.611111                25.000000      2024-01-30
3   168.000000   70.000000                10.000000      2023-12-24
4   160.000000   52.000000                30.000000      2023-12-30
5   172.000000   75.000000                12.000000      2023-12-19
6   158.000000   48.000000                35.000000      2024-01-31
7   180.000000   82.000000                18.000000      2024-01-19
8   163.000000   55.000000                22.000000      2024-01-13
9   167.000000   60.000000                28.000000      2024-01-26
10  167.684211   68.000000                21.388889      2024-02-05
11  171.000000   63.611111                16.000000      2023-12-25
12  169.000000   72.000000                24.000000      2024-01-22
13  164.000000   54.000000                19.000000      2024-01-14
14  162.000000   56.000000                26.000000      2024-01-06
15  173.000000   78.000000                14.000000      2024-01-25
16  166.000000   62.000000                21.000000      2024-01-29
17  161.000000   50.000000                27.000000      2024-02-02
18  174.000000   76.000000                21.388889      2023-12-21
19  168.000000   64.000000                23.000000      2023-12-21

In [20]:
Q1 = df_csv['GPA'].quantile(0.25)
Q3 = df_csv['GPA'].quantile(0.75)
IQR = Q3 - Q1

จัดการ GPA ที่ผิดปกติ เช่น ติดลบ และเติมเกรดของคนที่ไม่มีเกรด

In [21]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# กรองค่าผิดปกติ
df_no_outliers = df_csv[(df_csv['GPA'] >= lower_bound) & (df_csv['GPA'] <= upper_bound)]

print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - {df_no_outliers['GPA'].mean():.2f}")

ขอบเขตล่าง - 2.5324999999999998
ขอบเขตบน - 4.3525

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา    ชื่อ        อายุ   เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001   สมชาย   20.000000   ชาย     วิทยาศาสตร์  3.21  170.000000
1          64002  สมหญิง   21.000000  หญิง     วิทยาศาสตร์  3.45  165.000000
2          64003     NaN   28.470588   ชาย     วิทยาศาสตร์  3.67  175.000000
4          64005    สมใจ   19.000000  หญิง  วิศวกรรมศาสตร์  3.89  160.000000
5          64006   กานต์  150.000000   ชาย  วิศวกรรมศาสตร์  3.12  172.000000
7          64008    จิรา   20.000000  หญิง      ศิลปศาสตร์  2.98  180.000000
8          64009  ชนาธิป   23.000000   ชาย      ศิลปศาสตร์  3.34  163.000000
9          64010    ดารา   21.000000  หญิง      ศิลปศาสตร์  3.56  167.000000
10         64011    ธีระ   28.470588   ชาย     วิทยาศาสตร์  3.78  167.684211
12         64013   บุญมี   20.000000  หญิง  วิศวกรรมศาสตร์  3.23  169.000000
13         64014   ปรีชา   21.000000   ชาย      ศิลปศาสตร์  3.45  164.000000
14         64015   พิมพ์   22.000000  หญิง     วิทยาศาสตร์  3.67  162.000000
15         64016    ภูมิ   19.000000   ชาย     วิทยาศาสตร์  3.89  173.000000
16         64017    มานี   20.000000  หญิง  วิศวกรรมศาสตร์  3.01  166.000000
17         64018    ยุพา   21.000000  หญิง     วิทยาศาสตร์  3.23  161.000000
19         64020   ลัดดา   22.000000   ชาย     วิทยาศาสตร์  3.45  168.000000

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0    65.000000                15.000000      2024-02-06
1    58.000000                20.000000      2024-01-31
2    63.611111                25.000000      2024-01-30
4    52.000000                30.000000      2023-12-30
5    75.000000                12.000000      2023-12-19
7    82.000000                18.000000      2024-01-19
8    55.000000                22.000000      2024-01-13
9    60.000000                28.000000      2024-01-26
10   68.000000                21.388889      2024-02-05
12   72.000000                24.000000      2024-01-22
13   54.000000                19.000000      2024-01-14
14   56.000000                26.000000      2024-01-06
15   78.000000                14.000000      2024-01-25
16   62.000000                21.000000      2024-01-29
17   50.000000                27.000000      2024-02-02
19   64.000000                23.000000      2023-12-21

ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - 3.43

ลบแถวที่ชื่อเป็น NaN(ไม่ทราบ)

In [22]:
df_master_clean = df_no_outliers.dropna()
df_master_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.000000,65.0,15.000000,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.45,165.000000,58.0,20.000000,2024-01-31
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.89,160.000000,52.0,30.000000,2023-12-30
5,64006,กานต์,150.000000,ชาย,วิศวกรรมศาสตร์,3.12,172.000000,75.0,12.000000,2023-12-19
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.98,180.000000,82.0,18.000000,2024-01-19
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.34,163.000000,55.0,22.000000,2024-01-13
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.56,167.000000,60.0,28.000000,2024-01-26
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.78,167.684211,68.0,21.388889,2024-02-05
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.23,169.000000,72.0,24.000000,2024-01-22
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.45,164.000000,54.0,19.000000,2024-01-14
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.67,162.000000,56.0,26.000000,2024-01-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.89,173.000000,78.0,14.000000,2024-01-25
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.01,166.000000,62.0,21.000000,2024-01-29
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.23,161.000000,50.0,27.000000,2024-02-02
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.45,168.000000,64.0,23.000000,2023-12-21

รวม Features BMI,สุขภาพ รวมเข้ากับ df_master_clean

In [23]:
df_master_clean['BMI'] = df_master_clean['น้ำหนัก_kg'] / (df_master_clean['ส่วนสูง_cm']/100)**2
df_master_clean['สุขภาพ'] = pd.cut(df_master_clean['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

print(df_master_clean[['ชื่อ', 'BMI', 'สุขภาพ']])

      ชื่อ        BMI สุขภาพ
0    สมชาย  22.491349   ปกติ
1   สมหญิง  21.303949   ปกติ
4     สมใจ  20.312500   ปกติ
5    กานต์  25.351541   อ้วน
7     จิรา  25.308642   อ้วน
8   ชนาธิป  20.700817   ปกติ
9     ดารา  21.513859   ปกติ
10    ธีระ  24.183802   ปกติ
12   บุญมี  25.209201   อ้วน
13   ปรีชา  20.077335   ปกติ
14   พิมพ์  21.338211   ปกติ
15    ภูมิ  26.061679   อ้วน
16    มานี  22.499637   ปกติ
17    ยุพา  19.289379   ปกติ
19   ลัดดา  22.675737   ปกติ

In [24]:
df_master_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,BMI,สุขภาพ
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.000000,65.0,15.000000,2024-02-06,22.491349,ปกติ
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.45,165.000000,58.0,20.000000,2024-01-31,21.303949,ปกติ
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.89,160.000000,52.0,30.000000,2023-12-30,20.312500,ปกติ
5,64006,กานต์,150.000000,ชาย,วิศวกรรมศาสตร์,3.12,172.000000,75.0,12.000000,2023-12-19,25.351541,อ้วน
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.98,180.000000,82.0,18.000000,2024-01-19,25.308642,อ้วน
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.34,163.000000,55.0,22.000000,2024-01-13,20.700817,ปกติ
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.56,167.000000,60.0,28.000000,2024-01-26,21.513859,ปกติ
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.78,167.684211,68.0,21.388889,2024-02-05,24.183802,ปกติ
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.23,169.000000,72.0,24.000000,2024-01-22,25.209201,อ้วน
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.45,164.000000,54.0,19.000000,2024-01-14,20.077335,ปกติ
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.67,162.000000,56.0,26.000000,2024-01-06,21.338211,ปกติ
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.89,173.000000,78.0,14.000000,2024-01-25,26.061679,อ้วน
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.01,166.000000,62.0,21.000000,2024-01-29,22.499637,ปกติ
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.23,161.000000,50.0,27.000000,2024-02-02,19.289379,ปกติ
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.45,168.000000,64.0,23.000000,2023-12-21,22.675737,ปกติ

แปลงข้อมูลประเภท Boolean ในแถวคณะ เป็นตัวเลข

In [25]:
data_encoded = pd.get_dummies(df_master_clean, columns=['คณะ'])
data_encoded = data_encoded.replace({True: 1, False: 0})
data_encoded

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,BMI,สุขภาพ,คณะ_วิทยาศาสตร์,คณะ_วิศวกรรมศาสตร์,คณะ_ศิลปศาสตร์
0,64001,สมชาย,20.000000,ชาย,3.21,170.000000,65.0,15.000000,2024-02-06,22.491349,ปกติ,1,0,0
1,64002,สมหญิง,21.000000,หญิง,3.45,165.000000,58.0,20.000000,2024-01-31,21.303949,ปกติ,1,0,0
4,64005,สมใจ,19.000000,หญิง,3.89,160.000000,52.0,30.000000,2023-12-30,20.312500,ปกติ,0,1,0
5,64006,กานต์,150.000000,ชาย,3.12,172.000000,75.0,12.000000,2023-12-19,25.351541,อ้วน,0,1,0
7,64008,จิรา,20.000000,หญิง,2.98,180.000000,82.0,18.000000,2024-01-19,25.308642,อ้วน,0,0,1
8,64009,ชนาธิป,23.000000,ชาย,3.34,163.000000,55.0,22.000000,2024-01-13,20.700817,ปกติ,0,0,1
9,64010,ดารา,21.000000,หญิง,3.56,167.000000,60.0,28.000000,2024-01-26,21.513859,ปกติ,0,0,1
10,64011,ธีระ,28.470588,ชาย,3.78,167.684211,68.0,21.388889,2024-02-05,24.183802,ปกติ,1,0,0
12,64013,บุญมี,20.000000,หญิง,3.23,169.000000,72.0,24.000000,2024-01-22,25.209201,อ้วน,0,1,0
13,64014,ปรีชา,21.000000,ชาย,3.45,164.000000,54.0,19.000000,2024-01-14,20.077335,ปกติ,0,0,1
14,64015,พิมพ์,22.000000,หญิง,3.67,162.000000,56.0,26.000000,2024-01-06,21.338211,ปกติ,1,0,0
15,64016,ภูมิ,19.000000,ชาย,3.89,173.000000,78.0,14.000000,2024-01-25,26.061679,อ้วน,1,0,0
16,64017,มานี,20.000000,หญิง,3.01,166.000000,62.0,21.000000,2024-01-29,22.499637,ปกติ,0,1,0
17,64018,ยุพา,21.000000,หญิง,3.23,161.000000,50.0,27.000000,2024-02-02,19.289379,ปกติ,1,0,0
19,64020,ลัดดา,22.000000,ชาย,3.45,168.000000,64.0,23.000000,2023-12-21,22.675737,ปกติ,1,0,0

เพิ่มวันเวลา และ เพิ่มช่วงเวลาของชั่วโมงประจำสัปดาห์

In [26]:
data_encoded['วันในสัปดาห์'] = data_encoded['วันที่ลงทะเบียน'].dt.day_name()
data_encoded['ช่วงเวลา'] = pd.cut(data_encoded['ชั่วโมงเรียน_ต่อสัปดาห์'],
                                  bins=[0, 7, 14, 35],
                                  labels=['น้อย', 'ปานกลาง', 'มาก'])

data_encoded

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,BMI,สุขภาพ,คณะ_วิทยาศาสตร์,คณะ_วิศวกรรมศาสตร์,คณะ_ศิลปศาสตร์,วันในสัปดาห์,ช่วงเวลา
0,64001,สมชาย,20.000000,ชาย,3.21,170.000000,65.0,15.000000,2024-02-06,22.491349,ปกติ,1,0,0,Tuesday,มาก
1,64002,สมหญิง,21.000000,หญิง,3.45,165.000000,58.0,20.000000,2024-01-31,21.303949,ปกติ,1,0,0,Wednesday,มาก
4,64005,สมใจ,19.000000,หญิง,3.89,160.000000,52.0,30.000000,2023-12-30,20.312500,ปกติ,0,1,0,Saturday,มาก
5,64006,กานต์,150.000000,ชาย,3.12,172.000000,75.0,12.000000,2023-12-19,25.351541,อ้วน,0,1,0,Tuesday,ปานกลาง
7,64008,จิรา,20.000000,หญิง,2.98,180.000000,82.0,18.000000,2024-01-19,25.308642,อ้วน,0,0,1,Friday,มาก
8,64009,ชนาธิป,23.000000,ชาย,3.34,163.000000,55.0,22.000000,2024-01-13,20.700817,ปกติ,0,0,1,Saturday,มาก
9,64010,ดารา,21.000000,หญิง,3.56,167.000000,60.0,28.000000,2024-01-26,21.513859,ปกติ,0,0,1,Friday,มาก
10,64011,ธีระ,28.470588,ชาย,3.78,167.684211,68.0,21.388889,2024-02-05,24.183802,ปกติ,1,0,0,Monday,มาก
12,64013,บุญมี,20.000000,หญิง,3.23,169.000000,72.0,24.000000,2024-01-22,25.209201,อ้วน,0,1,0,Monday,มาก
13,64014,ปรีชา,21.000000,ชาย,3.45,164.000000,54.0,19.000000,2024-01-14,20.077335,ปกติ,0,0,1,Sunday,มาก
14,64015,พิมพ์,22.000000,หญิง,3.67,162.000000,56.0,26.000000,2024-01-06,21.338211,ปกติ,1,0,0,Saturday,มาก
15,64016,ภูมิ,19.000000,ชาย,3.89,173.000000,78.0,14.000000,2024-01-25,26.061679,อ้วน,1,0,0,Thursday,ปานกลาง
16,64017,มานี,20.000000,หญิง,3.01,166.000000,62.0,21.000000,2024-01-29,22.499637,ปกติ,0,1,0,Monday,มาก
17,64018,ยุพา,21.000000,หญิง,3.23,161.000000,50.0,27.000000,2024-02-02,19.289379,ปกติ,1,0,0,Friday,มาก
19,64020,ลัดดา,22.000000,ชาย,3.45,168.000000,64.0,23.000000,2023-12-21,22.675737,ปกติ,1,0,0,Thursday,มาก